language: python

# you can use Python 3.7 instead
python: "3.6"

# don't clone more than necessary
git:
  depth: 1

# Install any dependencies
install:
  - pip install -r requirements.txt

# script to run tests. Script can have many commands, one per line.
script:
  - coverage run -m unittest discover -p "*_test.py"

# An after_script section used to send the result to Codecov
after_script:
  - bash <(curl -s https://codecov.io/bash)